#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for nethgui-framework-update event
#--------------------------------------------------

$event = "nethgui-framework-update";

templates2events("/etc/sudoers", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
