#!/usr/bin/perl -w

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

#
# nethserver-httpd-admin-nethgui-update event
#
event_templates('nethserver-httpd-admin-nethgui-update', qw(
    /etc/httpd/admin-conf/httpd.conf
));

event_services('nethserver-httpd-admin-nethgui-update', qw(
    httpd-admin reload
));

#
# hostname-modify event
#
event_actions("hostname-modify", qw(
    nethserver-httpd-admin-smwingsd-restart 30
));
