#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

# conf-httpd-admin

templates2events("/etc/httpd/admin-conf/httpd.conf", qw(
	console-save
	bootstrap-console-save
	network-create
	network-delete
	remoteaccess-update
	logrotate
	));

# Set up generic logfile timestamp renaming/symlinking

foreach (qw(
    /var/log/httpd/admin_access_log
    /var/log/httpd/admin_error_log
    ))
{
    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp/$_";
    safe_touch "root/etc/e-smith/events/post-install/logfiles2timestamp/$_";
    safe_touch "root/etc/e-smith/events/post-upgrade/logfiles2timestamp/$_";
}

foreach (qw(console-save remoteaccess-update logrotate))
{
    safe_symlink("reload", "root/etc/e-smith/events/$_/services2adjust/httpd-admin");
}

foreach my $service (keys %service2order)
{
    service_link_enhanced($service, $service2order{$service}, 7);
}

# Symlink httpd-admin to httpd.
safe_symlink("httpd", "root/usr/sbin/httpd-admin");


