#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

my $event;

# Symlink httpd-admin to httpd.
safe_symlink("httpd", "root/usr/sbin/httpd-admin");

# conf-httpd-admin
templates2events("/etc/httpd/admin-conf/httpd.conf", (qw(
    console-save
    bootstrap-console-save
    network-create
    network-delete
    remoteaccess-update
    logrotate
)));

# Set up generic logfile timestamp renaming/symlinking
foreach (qw(
    /var/log/httpd/admin_access_log
    /var/log/httpd/admin_error_log
)) {
    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp" . $_;
    safe_touch "root/etc/e-smith/events/post-install/logfiles2timestamp" . $_;
    safe_touch "root/etc/e-smith/events/post-upgrade/logfiles2timestamp" . $_;
}

safe_symlink("reload", "root/etc/e-smith/events/$_/services2adjust/httpd-admin") foreach(qw(
    console-save
    network-create
    network-delete
    remoteaccess-update
    logrotate
));

# package update event:
event_templates('nethserver-httpd-admin-update',
		'/etc/httpd/admin-conf/httpd.conf',
		'/etc/sudoers');

event_actions('nethserver-httpd-admin-update',
	      "initialize-default-databases" => '05',
	      "runlevel-adjust" => '50',
	      "firewall-adjust" => '55');
	      
# restart httpd-admin
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/httpd-admin") 
    foreach $event (qw(
        nethserver-httpd-admin-update
        bootstrap-console-save
));
