#!/usr/bin/perl -w

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

my @certificates = (qw(
                /etc/pki/tls/private/httpd-admin.key
                /etc/pki/tls/certs/httpd-admin.crt
));

#
# nethserver-httpd-admin-update event:
#
event_templates('nethserver-httpd-admin-update', qw(
		/etc/httpd/admin-conf/httpd.conf
), @certificates);

event_actions('nethserver-httpd-admin-update', qw(
	      initialize-default-databases 00
              nethserver-httpd-admin-conf 20
));

event_services('nethserver-httpd-admin-update', qw(
    httpd-admin reload
));
 
#
# certificate-update event
#
event_templates('certificate-update', @certificates);
event_templates('certificate-update', '/etc/httpd/admin-conf/httpd.conf');

event_actions('certificate-update', qw(
       nethserver-httpd-admin-asyncreload 99
));

#
# system-init event
#
event_actions("system-init", qw(
   enable-firstconfigwizard 20
));


#--------------------------------------------------
# actions for hostname-modify event
#--------------------------------------------------
event_actions("hostname-modify", qw(nethserver-httpd-admin-smwingsd-restart 30));
